### ISSUE TITLE
Help Pls

### ISSUE THREAD

**Issue by shadow-mafi** [risporce/Supercell-jailbreak#73]
**first i got this error** 

```
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x1218
[INFO] Found string table fixing address at: 0x2461fe8
[INFO] Found symbol table start address at: 0x2662290
[INFO] Found protector loader at: 0x1348
Traceback (most recent call last):
  File "C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main\sc_protector_file_parser.py", line 411, in <module>
    main(game)
  File "C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main\sc_protector_file_parser.py", line 271, in main
    pid = device.spawn([f"com.supercell.{game}"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1029, in spawn
    return self._impl.spawn(program, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unable to launch iOS app via FBS: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "com.supercell.None"
```

**but i fixed it by manually writing the package name of the game i want in the script in line 271 but after that i got this error i have no idea what is this** 

```
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x1218
[INFO] Found string table fixing address at: 0x2461fe8
[INFO] Found symbol table start address at: 0x2662290
[INFO] Found protector loader at: 0x1348
[ERROR] TypeError: cannot read property 'add' of null
    at <eval> (/script1.js:8)
[INFO] setup done, don't exit, the computer can take up to a minute to exit frida session
```

**i can share my folder content too** 

<img width="522" alt="2024-11-02 20_18_14-Supercell-jailbreak-main - File Explorer" src="https://github.com/user-attachments/assets/9b3e1476-186b-434c-8117-db709f0a65a4">

**the command that i used = python sc_protector_file_parser.py --game "hay day"**

**Comment by risporce** [comment]
Hi, you got the command and setup correct, but the name string for the --game parameter is case sensitive  so you really should write "Hay Day" for the association to match correctly. I'll try to fix that for the next update
