### ISSUE TITLE
Fix This Please

### ISSUE THREAD

**Issue by shadow-mafi** [risporce/Supercell-jailbreak#74]
**hi when i enter the command i get this error** 

```
C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main>python sc_protector_file_parser.py --game "Hay Day"
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x1218
[INFO] Found string table fixing address at: 0x2461fe8
[INFO] Found symbol table start address at: 0x2662290
[INFO] Found protector loader at: 0x1348
Traceback (most recent call last):
  File "C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main\sc_protector_file_parser.py", line 410, in <module>
    main(game)
  File "C:\Users\shado\Downloads\Supercell-jailbreak-main\Supercell-jailbreak-main\sc_protector_file_parser.py", line 269, in main
    device = frida.get_usb_device()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\__init__.py", line 137, in get_usb_device
    return get_device_manager().get_usb_device(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1229, in get_usb_device
    return self.get_device_matching(lambda d: d.type == "usb", timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shado\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1252, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.InvalidArgumentError: device not found
```
i fixed this by executing command and connecting the usb cable at the same time but it would be good if there was an easier fix or method for this

**Comment by risporce** [comment]
Hi, well there’s nothing for me to fix here, the script is working as intended, if you have trouble connecting your device to your computer you should try to use another cable example Apple Original cable if still in good condition.
