### ISSUE TITLE
phone crash upon running script

### ISSUE THREAD

**Issue by goomey** [risporce/Supercell-jailbreak#79]
I assume I'm doing something wrong and the script isn't causing the crash but I'm really at a loss here I don't know what to do anymore.
doing frida-ps -U works fine and prints the list
when I run the script however, the phone almost immediately shuts off and reboots

C:\Windows\System32\Supercell-jailbreak>py sc_protector_file_parser.py --game "Clash of Clans"
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x11c8
[INFO] Found string table fixing address at: 0x127ac28
[INFO] Found symbol table start address at: 0x13a3628
[INFO] Found protector loader at: 0x12f8
Traceback (most recent call last):
  File "C:\Windows\System32\Supercell-jailbreak\sc_protector_file_parser.py", line 454, in <module>
    main(game)
  File "C:\Windows\System32\Supercell-jailbreak\sc_protector_file_parser.py", line 311, in main
    device = frida.get_usb_device()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\frida\__init__.py", line 137, in get_usb_device
    return get_device_manager().get_usb_device(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\frida\core.py", line 1229, in get_usb_device
    return self.get_device_matching(lambda d: d.type == "usb", timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\frida\core.py", line 1252, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.InvalidArgumentError: device not found

**Comment by rldv1** [comment]
What iPhone do you have? (including iOS version), and what jailbreak do you have installed?

**Comment by goomey** [comment]
iphone 11 pro ios 14.2 taurine jailbreak

**Comment by risporce** [comment]
Sorry but I can’t really help you other than saying to make sure your jailbreak environment is working properly/stable , some other tweaks injected into the process may cause issue with Frida.

**Comment by Alzentane** [comment]
Change to unc0ver 6.1.2 
I had same issue as you
